name: Java Make New Release

on:
  push:
    tags:
      - Release-**

jobs:
  build:
    strategy:
      matrix:
        version: [ 11, 17 ]
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'oracle'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
